In [1]:
pip install numpy sympy matplotlib jax ipykernel

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 28.4 MB/s  0:00:00m0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 15.3 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 30.1 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 MB 34.8 MB/s  0:00:026m0:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6/6 [jax]5/6 [jax]ib]sum]
Note: you may need to restart the kernel to use updated packages.


In [2]:
# %%
import numpy, sympy, jax
print(numpy.__version__, sympy.__version__, jax.__version__)

2.5.3 1.14.0 0.11.2


In [24]:
from sympy import symbols, exp, sin, diff
x = symbols('x')
f_exp = x ** 2
print(f_exp)

g_expr = exp(-2 * x) + (3 * sin(3 * x))
print(g_expr)

df_expr = diff(f_exp)
dg_expr = diff(g_expr)

print(df_expr, dg_expr)


x**2
3*sin(3*x) + exp(-2*x)
2*x 9*cos(3*x) - 2*exp(-2*x)


In [40]:
import numpy as np
from sympy import lambdify
print(dg_expr.evalf(subs={x:1}))
dg_func = lambdify(x,dg_expr,'numpy')
a = np.array([1,2,3])
dg_func(a)




-9.18060303587724


array([-9.18060304,  8.6049013 , -8.20512986])

In [48]:
func = (abs(x))
der_func = diff(func)
func_1 = lambdify(x,der_func,'numpy')
func_1(10)

PrintMethodNotImplementedError: Unsupported by <class 'sympy.printing.numpy.NumPyPrinter'>: <class 'sympy.core.function.Derivative'>
Printer has no method: _print_Derivative_re
Set the printer option 'strict' to False in order to generate partially printed code.

In [51]:
xr = symbols('x', real=True)
func_r = abs(xr)
der_r = diff(func_r)
print(der_r)
func_2 = lambdify(xr, der_r, 'numpy')
func_2(np.array([-2., 0., 2.]))

sign(x)


array([-1.,  0.,  1.])

** Numpy Based Derivatives**

In [65]:
import numpy as np

x = np.linspace(-5, 5, 100)
x_square = x ** 2
slopes = np.gradient(x_square,x)
#print(slopes)

difference = np.abs(slopes - 2*x)
np.max(difference)

np.float64(0.10101010101011276)

In [71]:
x_abs = np.abs(x)
#print(x_abs)
slopes = np.gradient(x_abs)
slopes[47:53]

array([-0.1010101 , -0.1010101 , -0.05050505,  0.05050505,  0.1010101 ,
        0.1010101 ])

In [92]:
import jax.numpy as jnp
from jax import grad, vmap


def function (x):
    return x**2

df = grad(function)
print(df(3.0))

6.0


In [100]:
a = jnp.array([1.0,2.0,3.0])
df_many = vmap(df)
print(df_many)
print(df_many(a))

<function function at 0x70f644149c70>
[2. 4. 6.]
